### ISSUE TITLE
build with qwt 6.2.0 fails

### ISSUE THREAD

**Issue by brokensoard** [ShaneFlandermeyer/gr-plasma#9]
when running make I get the following error:

In file included from /home/ric/Documents/gr-plasma/gr-plasma/build/lib/gnuradioplasma_autogen/EWIEGA46WW/moc_range_doppler_window.cpp:10,
                 from /home/ric/Documents/gr-plasma/gr-plasma/build/lib/gnuradio-plasma_autogen/mocs_compilation.cpp:2:
/home/ric/Documents/gr-plasma/gr-plasma/build/lib/gnuradio-plasma_autogen/EWIEGA46WW/../../../../lib/range_doppler_window.h: In member function ‘virtual void RangeDopplerData::setInterval(Qt::Axis, const QwtInterval&)’:
/home/ric/Documents/gr-plasma/gr-plasma/build/lib/gnuradio-plasma_autogen/EWIEGA46WW/../../../../lib/range_doppler_window.h:56:24: error: ‘setInterval’ is not a member of ‘QwtRasterData’
   56 |         QwtRasterData::setInterval(axis, interval);
      |                        ^~~~~~~~~~~
make[2]: *** [lib/CMakeFiles/gnuradio-plasma.dir/build.make:82: lib/CMakeFiles/gnuradio-plasma.dir/gnuradio-plasma_autogen/mocs_compilation.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:249: lib/CMakeFiles/gnuradio-plasma.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
 
I have qwt 6.2 installed using conda, I am guessing the qwt libraries have changed.  What version of qwt was used during the initial build?

**Comment by ShaneFlandermeyer** [comment]
Apologies for the late response on this. I installed qwt using apt, and my version is: libqwt-qt5-dev/jammy,now 6.1.4-2 amd64 [installed]

I will add this to the installation section of the readme. Let me know if that doesn't work

**Comment by brokensoard** [comment]
Thank you for the reply.  I changed the line to QwtMatrixRasterData::setInterval(axis, interval); which let me compile, I am waiting on access to a usrp radio to test.
